"""empty message

Revision ID: e71e93de84b0
Revises: a3bbae8b639e
Create Date: 2022-08-08 00:04:45.370144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e71e93de84b0'
down_revision = 'a3bbae8b639e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'authors', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'authors', type_='foreignkey')
    op.drop_column('authors', 'user_id')
    # ### end Alembic commands ###
